name: CI Build Ravenfall-Server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-dotnet:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: v5.0.100-preview.7
    - name: Install dependencies
      run: dotnet restore "Ravenfall Server.sln"
    - name: Build
      run: dotnet build --configuration Release --no-restore "Ravenfall Server.sln"
